// Code generated by scripts/regen-catalog.py; DO NOT EDIT.
// Universal Blue / Project Bluefin / TunaOS images, freshness-filtered to
// tags built within 60 days. Regenerate with `just regen-catalog`.

package catalog

var generatedBootcImages = []BootcImage{}

var generatedISOs = []Image{
	{Name: "bluefin-iso", Description: "Bluefin — GNOME bootc desktop (installer ISO)", ISO: "https://download.projectbluefin.io/bluefin-stable-x86_64.iso", Source: "projectbluefin.io", Logo: "gnome", Variant: "desktop"},
	{Name: "aurora-iso", Description: "Aurora — KDE Plasma bootc desktop (installer ISO)", ISO: "https://dl.getaurora.dev/aurora-stable-webui-x86_64.iso", Source: "getaurora.dev", Logo: "kde", Variant: "desktop"},
	{Name: "aurora-nvidia-open-iso", Description: "Aurora — KDE, NVIDIA open driver (installer ISO)", ISO: "https://dl.getaurora.dev/aurora-nvidia-open-stable-webui-x86_64.iso", Source: "getaurora.dev", Logo: "kde", Variant: "desktop"},
}
